[package]
name = "pullomatic"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]

[dependencies]
git2 = "0.7"

toml = "0.4"
serde = "1.0"
serde_derive = "1.0"

ctrlc = { version = "3.0", features = ["termination"]}

rouille = "2.1"

