[package]
name = "pullomatic"
version = "0.1.0"
authors = ["Dustin Frisch <fooker@lab.sh>"]

[dependencies]
git2 = { version = "0.7", git = "https://github.com/fooker/git2-rs.git" }

toml = "0.4"
serde = "1.0"
serde_derive = "1.0"

ctrlc = { version = "3.0", features = ["termination"]}

rouille = "2.1"

serde-humantime = "0.1.1"
